# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u4e3b\u673a\u540d')),
                ('ip', models.CharField(max_length=50, verbose_name='IP\u5730\u5740')),
                ('kn', models.CharField(max_length=50, verbose_name='\u5185\u6838\u7248\u672c')),
                ('release', models.CharField(max_length=50, verbose_name='centos\u7248\u672c')),
                ('disk', models.CharField(max_length=50, verbose_name='\u78c1\u76d8\u7a7a\u95f4\u603b\u91cf')),
                ('mem', models.CharField(max_length=50, verbose_name='\u5185\u5b58\u603b\u91cf')),
            ],
        ),
    ]
