# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostinfo', '0002_auto_20160511_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='disk',
        ),
    ]
